server.servlet.context-path=/tienda-ropa
# Le dice a Spring a qué base de datos conectarse.
spring.datasource.url=jdbc:h2:mem:shop;DATABASE_TO_LOWER=TRUE
# Indica el "traductor" (driver) exacto que debe usar Java para hablar con la base de datos H2.
spring.datasource.driver-class-name=org.h2.Driver
# Usuario por defecto (sa = System Administrator) y contraseña en blanco.
spring.datasource.username=sa
spring.datasource.password=

# Le dice a Hibernate el "dialecto" que debe usar. Así sabe exactamente cómo escribir las
# sentencias SQL para que H2 las entienda (cada base de datos tiene sus pequeñas diferencias).
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Hace que Spring lea tus clases @Entity y cree o actualice las tablas automáticamente en la base de datos sin borrar los datos que ya haya.
spring.jpa.hibernate.ddl-auto=update
# Hacen que cada vez que Spring haga una consulta a la base de datos, la imprima en la consola de tu IDE (show-sql=true) y además la ponga bonita y tabulada (format_sql=true).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Espera a que Hibernate haya terminado de crear TODAS las tablas ANTES de ejecutar el archivo data.sql
spring.jpa.defer-datasource-initialization=true
# Activa una interfaz visual en el navegador para que puedas ver tus tablas y hacer SELECTs a mano.
spring.h2.console.enabled=true
# Define la ruta para entrar a esa consola localhost:8080/tienda-ropa/h2-console
spring.h2.console.path=/h2-console